/*
**  ROMS input file generated by fabm_roms....py                                      **
**  Assigns metadata indices for the FABM model variables that are used in NetCDF IO  **
**  The metadata information is read from "varinfo.dat"                               **
**  This file is included in file "mod_ncparam.F", routine "initialize_ncparm"        **
**  Phil Wallhead, NIVA (2015)  **
*/

/*
**  Model state biological tracers.
*/
#ifdef DEBUG
            write(*,*) "Assigning idTvar in rfabm_var.h"
#endif
              CASE('idTvar(iB_OXYDEP_Oxy)')
                idTvar(iB_OXYDEP_Oxy) = varid
              CASE('idTvar(iB_OXYDEP_Phy)')
                idTvar(iB_OXYDEP_Phy) = varid
              CASE('idTvar(iB_OXYDEP_NUT)')
                idTvar(iB_OXYDEP_NUT) = varid
              CASE('idTvar(iB_OXYDEP_POM)')
                idTvar(iB_OXYDEP_POM) = varid
              CASE('idTvar(iB_OXYDEP_DOM)')
                idTvar(iB_OXYDEP_DOM) = varid
              CASE('idTvar(iB_OXYDEP_Het)')
                idTvar(iB_OXYDEP_Het) = varid
              CASE('idTvar(iB_BIOPLAST_MP_free)')
                idTvar(iB_BIOPLAST_MP_free) = varid
              CASE('idTvar(iB_BIOPLAST_MP_biof)')
                idTvar(iB_BIOPLAST_MP_biof) = varid
              CASE('idTvar(iB_BIOPLAST_MP_het)')
                idTvar(iB_BIOPLAST_MP_het) = varid
              CASE('idTvar(iB_BIOPLAST_MP_det)')
                idTvar(iB_BIOPLAST_MP_det) = varid

/*
**  Adjoint sensitivity state biological tracers.
*/

#if defined AD_SENSITIVITY   || defined IS4DVAR_SENSITIVITY || \
    defined OPT_OBSERVATIONS || defined SENSITIVITY_4DVAR   || \
    defined SO_SEMI

/*
**  Adjoint sensitivity.
*/
#ifdef DEBUG
            write(*,*) "Assigning idTads in rfabm_var.h"
#endif
              CASE('idTads(iB_OXYDEP_Oxy)')
                idTads(iB_OXYDEP_Oxy) = varid
              CASE('idTads(iB_OXYDEP_Phy)')
                idTads(iB_OXYDEP_Phy) = varid
              CASE('idTads(iB_OXYDEP_NUT)')
                idTads(iB_OXYDEP_NUT) = varid
              CASE('idTads(iB_OXYDEP_POM)')
                idTads(iB_OXYDEP_POM) = varid
              CASE('idTads(iB_OXYDEP_DOM)')
                idTads(iB_OXYDEP_DOM) = varid
              CASE('idTads(iB_OXYDEP_Het)')
                idTads(iB_OXYDEP_Het) = varid
              CASE('idTads(iB_BIOPLAST_MP_free)')
                idTads(iB_BIOPLAST_MP_free) = varid
              CASE('idTads(iB_BIOPLAST_MP_biof)')
                idTads(iB_BIOPLAST_MP_biof) = varid
              CASE('idTads(iB_BIOPLAST_MP_het)')
                idTads(iB_BIOPLAST_MP_het) = varid
              CASE('idTads(iB_BIOPLAST_MP_det)')
                idTads(iB_BIOPLAST_MP_det) = varid
#endif
/*
**  Biological tracers open boundary conditions.
*/
#ifdef DEBUG
            write(*,*) "Assigning idTbry in rfabm_var.h"
#endif
              CASE('idTbry(iwest,iB_OXYDEP_Oxy)')
                idTbry(iwest,iB_OXYDEP_Oxy) = varid
              CASE('idTbry(ieast,iB_OXYDEP_Oxy)')
                idTbry(ieast,iB_OXYDEP_Oxy) = varid
              CASE('idTbry(isouth,iB_OXYDEP_Oxy)')
                idTbry(isouth,iB_OXYDEP_Oxy) = varid
              CASE('idTbry(inorth,iB_OXYDEP_Oxy)')
                idTbry(inorth,iB_OXYDEP_Oxy) = varid

              CASE('idTbry(iwest,iB_OXYDEP_Phy)')
                idTbry(iwest,iB_OXYDEP_Phy) = varid
              CASE('idTbry(ieast,iB_OXYDEP_Phy)')
                idTbry(ieast,iB_OXYDEP_Phy) = varid
              CASE('idTbry(isouth,iB_OXYDEP_Phy)')
                idTbry(isouth,iB_OXYDEP_Phy) = varid
              CASE('idTbry(inorth,iB_OXYDEP_Phy)')
                idTbry(inorth,iB_OXYDEP_Phy) = varid

              CASE('idTbry(iwest,iB_OXYDEP_NUT)')
                idTbry(iwest,iB_OXYDEP_NUT) = varid
              CASE('idTbry(ieast,iB_OXYDEP_NUT)')
                idTbry(ieast,iB_OXYDEP_NUT) = varid
              CASE('idTbry(isouth,iB_OXYDEP_NUT)')
                idTbry(isouth,iB_OXYDEP_NUT) = varid
              CASE('idTbry(inorth,iB_OXYDEP_NUT)')
                idTbry(inorth,iB_OXYDEP_NUT) = varid

              CASE('idTbry(iwest,iB_OXYDEP_POM)')
                idTbry(iwest,iB_OXYDEP_POM) = varid
              CASE('idTbry(ieast,iB_OXYDEP_POM)')
                idTbry(ieast,iB_OXYDEP_POM) = varid
              CASE('idTbry(isouth,iB_OXYDEP_POM)')
                idTbry(isouth,iB_OXYDEP_POM) = varid
              CASE('idTbry(inorth,iB_OXYDEP_POM)')
                idTbry(inorth,iB_OXYDEP_POM) = varid

              CASE('idTbry(iwest,iB_OXYDEP_DOM)')
                idTbry(iwest,iB_OXYDEP_DOM) = varid
              CASE('idTbry(ieast,iB_OXYDEP_DOM)')
                idTbry(ieast,iB_OXYDEP_DOM) = varid
              CASE('idTbry(isouth,iB_OXYDEP_DOM)')
                idTbry(isouth,iB_OXYDEP_DOM) = varid
              CASE('idTbry(inorth,iB_OXYDEP_DOM)')
                idTbry(inorth,iB_OXYDEP_DOM) = varid

              CASE('idTbry(iwest,iB_OXYDEP_Het)')
                idTbry(iwest,iB_OXYDEP_Het) = varid
              CASE('idTbry(ieast,iB_OXYDEP_Het)')
                idTbry(ieast,iB_OXYDEP_Het) = varid
              CASE('idTbry(isouth,iB_OXYDEP_Het)')
                idTbry(isouth,iB_OXYDEP_Het) = varid
              CASE('idTbry(inorth,iB_OXYDEP_Het)')
                idTbry(inorth,iB_OXYDEP_Het) = varid

              CASE('idTbry(iwest,iB_BIOPLAST_MP_free)')
                idTbry(iwest,iB_BIOPLAST_MP_free) = varid
              CASE('idTbry(ieast,iB_BIOPLAST_MP_free)')
                idTbry(ieast,iB_BIOPLAST_MP_free) = varid
              CASE('idTbry(isouth,iB_BIOPLAST_MP_free)')
                idTbry(isouth,iB_BIOPLAST_MP_free) = varid
              CASE('idTbry(inorth,iB_BIOPLAST_MP_free)')
                idTbry(inorth,iB_BIOPLAST_MP_free) = varid

              CASE('idTbry(iwest,iB_BIOPLAST_MP_biof)')
                idTbry(iwest,iB_BIOPLAST_MP_biof) = varid
              CASE('idTbry(ieast,iB_BIOPLAST_MP_biof)')
                idTbry(ieast,iB_BIOPLAST_MP_biof) = varid
              CASE('idTbry(isouth,iB_BIOPLAST_MP_biof)')
                idTbry(isouth,iB_BIOPLAST_MP_biof) = varid
              CASE('idTbry(inorth,iB_BIOPLAST_MP_biof)')
                idTbry(inorth,iB_BIOPLAST_MP_biof) = varid

              CASE('idTbry(iwest,iB_BIOPLAST_MP_het)')
                idTbry(iwest,iB_BIOPLAST_MP_het) = varid
              CASE('idTbry(ieast,iB_BIOPLAST_MP_het)')
                idTbry(ieast,iB_BIOPLAST_MP_het) = varid
              CASE('idTbry(isouth,iB_BIOPLAST_MP_het)')
                idTbry(isouth,iB_BIOPLAST_MP_het) = varid
              CASE('idTbry(inorth,iB_BIOPLAST_MP_het)')
                idTbry(inorth,iB_BIOPLAST_MP_het) = varid

              CASE('idTbry(iwest,iB_BIOPLAST_MP_det)')
                idTbry(iwest,iB_BIOPLAST_MP_det) = varid
              CASE('idTbry(ieast,iB_BIOPLAST_MP_det)')
                idTbry(ieast,iB_BIOPLAST_MP_det) = varid
              CASE('idTbry(isouth,iB_BIOPLAST_MP_det)')
                idTbry(isouth,iB_BIOPLAST_MP_det) = varid
              CASE('idTbry(inorth,iB_BIOPLAST_MP_det)')
                idTbry(inorth,iB_BIOPLAST_MP_det) = varid


/*
**  Biological tracers point Source/Sinks (river runoff)..
*/
#ifdef DEBUG
            write(*,*) "Assigning idRtrc in rfabm_var.h"
#endif
              CASE('idRtrc(iB_OXYDEP_Oxy)')
                idRtrc(iB_OXYDEP_Oxy) = varid
              CASE('idRtrc(iB_OXYDEP_Phy)')
                idRtrc(iB_OXYDEP_Phy) = varid
              CASE('idRtrc(iB_OXYDEP_NUT)')
                idRtrc(iB_OXYDEP_NUT) = varid
              CASE('idRtrc(iB_OXYDEP_POM)')
                idRtrc(iB_OXYDEP_POM) = varid
              CASE('idRtrc(iB_OXYDEP_DOM)')
                idRtrc(iB_OXYDEP_DOM) = varid
              CASE('idRtrc(iB_OXYDEP_Het)')
                idRtrc(iB_OXYDEP_Het) = varid
              CASE('idRtrc(iB_BIOPLAST_MP_free)')
                idRtrc(iB_BIOPLAST_MP_free) = varid
              CASE('idRtrc(iB_BIOPLAST_MP_biof)')
                idRtrc(iB_BIOPLAST_MP_biof) = varid
              CASE('idRtrc(iB_BIOPLAST_MP_het)')
                idRtrc(iB_BIOPLAST_MP_het) = varid
              CASE('idRtrc(iB_BIOPLAST_MP_det)')
                idRtrc(iB_BIOPLAST_MP_det) = varid

#ifdef TS_ISOURCE
/*
**  Biological tracers internal point Source/Sinks (e.g. fish farms)..
*/
#ifdef DEBUG
            write(*,*) "Assigning idItrc in rfabm_var.h"
#endif
              CASE('idItrc(iB_OXYDEP_Oxy)')
                idItrc(iB_OXYDEP_Oxy) = varid
              CASE('idItrc(iB_OXYDEP_Phy)')
                idItrc(iB_OXYDEP_Phy) = varid
              CASE('idItrc(iB_OXYDEP_NUT)')
                idItrc(iB_OXYDEP_NUT) = varid
              CASE('idItrc(iB_OXYDEP_POM)')
                idItrc(iB_OXYDEP_POM) = varid
              CASE('idItrc(iB_OXYDEP_DOM)')
                idItrc(iB_OXYDEP_DOM) = varid
              CASE('idItrc(iB_OXYDEP_Het)')
                idItrc(iB_OXYDEP_Het) = varid
              CASE('idItrc(iB_BIOPLAST_MP_free)')
                idItrc(iB_BIOPLAST_MP_free) = varid
              CASE('idItrc(iB_BIOPLAST_MP_biof)')
                idItrc(iB_BIOPLAST_MP_biof) = varid
              CASE('idItrc(iB_BIOPLAST_MP_het)')
                idItrc(iB_BIOPLAST_MP_het) = varid
              CASE('idItrc(iB_BIOPLAST_MP_det)')
                idItrc(iB_BIOPLAST_MP_det) = varid
#endif

#ifdef DIAGNOSTICS_BIO
!
!  FABM horizontal diagnostic variables
!

#ifdef DEBUG
            write(*,*) "Assigning iDbio2 in rfabm_var.h"
#endif

!
!  FABM interior diagnostic variables
!

#ifdef DEBUG
            write(*,*) "Assigning iDbio3 in rfabm_var.h"
#endif
            CASE(                                                       &
     & 'iDbio3(iB_OXYDEP_GrazPhy)')
              iDbio3(                                                   &
     & iB_OXYDEP_GrazPhy)=varid
            CASE(                                                       &
     & 'iDbio3(iB_OXYDEP_GrazPOM)')
              iDbio3(                                                   &
     & iB_OXYDEP_GrazPOM)=varid
            CASE(                                                       &
     & 'iDbio3(iB_OXYDEP_LimN)')
              iDbio3(                                                   &
     & iB_OXYDEP_LimN)=varid
            CASE(                                                       &
     & 'iDbio3(iB_OXYDEP_LimT)')
              iDbio3(                                                   &
     & iB_OXYDEP_LimT)=varid
            CASE(                                                       &
     & 'iDbio3(iB_OXYDEP_LimLight)')
              iDbio3(                                                   &
     & iB_OXYDEP_LimLight)=varid
            CASE(                                                       &
     & 'iDbio3(iB_OXYDEP_GrowthPhy)')
              iDbio3(                                                   &
     & iB_OXYDEP_GrowthPhy)=varid
            CASE(                                                       &
     & 'iDbio3(iB_OXYDEP_DOM_decay_ox)')
              iDbio3(                                                   &
     & iB_OXYDEP_DOM_decay_ox)=varid
            CASE(                                                       &
     & 'iDbio3(iB_OXYDEP_DOM_decay_denitr)')
              iDbio3(                                                   &
     & iB_OXYDEP_DOM_decay_denitr)=varid
            CASE(                                                       &
     & 'iDbio3(iB_OXYDEP_POM_decay_denitr)')
              iDbio3(                                                   &
     & iB_OXYDEP_POM_decay_denitr)=varid
            CASE(                                                       &
     & 'iDbio3(iB_OXYDEP_Autolys)')
              iDbio3(                                                   &
     & iB_OXYDEP_Autolys)=varid
#endif
#ifdef DEBUG
            write(*,*) "Done assigning ids in rfabm_var.h"
#endif
