/*
**  ROMS input file generated by fabm_roms_input_from_yaml.py                         **
**  Assigns metadata indices for the FABM model variables that are used in NetCDF IO  **
**  The metadata information is read from "varinfo.dat"                               **
**  This file is included in file "mod_ncparam.F", routine "initialize_ncparm"        **
**  Phil Wallhead, NIVA (2015)  **
*/

/*
**  Model state biological tracers.
*/

      write(*,*) "Assigning varids in rfabm_var.h -PWA"

              CASE('idTvar(iN1_p)')
                idTvar(iN1_p) = varid
              CASE('idTvar(iN3_n)')
                idTvar(iN3_n) = varid
              CASE('idTvar(iN4_n)')
                idTvar(iN4_n) = varid
              CASE('idTvar(iN5_s)')
                idTvar(iN5_s) = varid
              CASE('idTvar(iO2_o)')
                idTvar(iO2_o) = varid
              CASE('idTvar(iO3_c)')
                idTvar(iO3_c) = varid
              CASE('idTvar(iO3_TA)')
                idTvar(iO3_TA) = varid
              CASE('idTvar(iR1_c)')
                idTvar(iR1_c) = varid
              CASE('idTvar(iR1_n)')
                idTvar(iR1_n) = varid
              CASE('idTvar(iR1_p)')
                idTvar(iR1_p) = varid
              CASE('idTvar(iR2_c)')
                idTvar(iR2_c) = varid
              CASE('idTvar(iR3_c)')
                idTvar(iR3_c) = varid
              CASE('idTvar(iR4_c)')
                idTvar(iR4_c) = varid
              CASE('idTvar(iR4_n)')
                idTvar(iR4_n) = varid
              CASE('idTvar(iR4_p)')
                idTvar(iR4_p) = varid
              CASE('idTvar(iR6_c)')
                idTvar(iR6_c) = varid
              CASE('idTvar(iR6_n)')
                idTvar(iR6_n) = varid
              CASE('idTvar(iR6_p)')
                idTvar(iR6_p) = varid
              CASE('idTvar(iR6_s)')
                idTvar(iR6_s) = varid
              CASE('idTvar(iR8_c)')
                idTvar(iR8_c) = varid
              CASE('idTvar(iR8_n)')
                idTvar(iR8_n) = varid
              CASE('idTvar(iR8_p)')
                idTvar(iR8_p) = varid
              CASE('idTvar(iR8_s)')
                idTvar(iR8_s) = varid
              CASE('idTvar(iB1_c)')
                idTvar(iB1_c) = varid
              CASE('idTvar(iB1_n)')
                idTvar(iB1_n) = varid
              CASE('idTvar(iB1_p)')
                idTvar(iB1_p) = varid
              CASE('idTvar(iP1_c)')
                idTvar(iP1_c) = varid
              CASE('idTvar(iP1_n)')
                idTvar(iP1_n) = varid
              CASE('idTvar(iP1_p)')
                idTvar(iP1_p) = varid
              CASE('idTvar(iP1_Chl)')
                idTvar(iP1_Chl) = varid
              CASE('idTvar(iP1_s)')
                idTvar(iP1_s) = varid
              CASE('idTvar(iL2_c)')
                idTvar(iL2_c) = varid
              CASE('idTvar(iP2_c)')
                idTvar(iP2_c) = varid
              CASE('idTvar(iP2_n)')
                idTvar(iP2_n) = varid
              CASE('idTvar(iP2_p)')
                idTvar(iP2_p) = varid
              CASE('idTvar(iP2_Chl)')
                idTvar(iP2_Chl) = varid
              CASE('idTvar(iP3_c)')
                idTvar(iP3_c) = varid
              CASE('idTvar(iP3_n)')
                idTvar(iP3_n) = varid
              CASE('idTvar(iP3_p)')
                idTvar(iP3_p) = varid
              CASE('idTvar(iP3_Chl)')
                idTvar(iP3_Chl) = varid
              CASE('idTvar(iP4_c)')
                idTvar(iP4_c) = varid
              CASE('idTvar(iP4_n)')
                idTvar(iP4_n) = varid
              CASE('idTvar(iP4_p)')
                idTvar(iP4_p) = varid
              CASE('idTvar(iP4_Chl)')
                idTvar(iP4_Chl) = varid
              CASE('idTvar(iZ4_c)')
                idTvar(iZ4_c) = varid
              CASE('idTvar(iZ5_c)')
                idTvar(iZ5_c) = varid
              CASE('idTvar(iZ5_n)')
                idTvar(iZ5_n) = varid
              CASE('idTvar(iZ5_p)')
                idTvar(iZ5_p) = varid
              CASE('idTvar(iZ6_c)')
                idTvar(iZ6_c) = varid
              CASE('idTvar(iZ6_n)')
                idTvar(iZ6_n) = varid
              CASE('idTvar(iZ6_p)')
                idTvar(iZ6_p) = varid


              CASE('idTclm(iN1_p)')
                idTclm(iN1_p) = varid
              CASE('idTclm(iN3_n)')
                idTclm(iN3_n) = varid
              CASE('idTclm(iN4_n)')
                idTclm(iN4_n) = varid
              CASE('idTclm(iN5_s)')
                idTclm(iN5_s) = varid
              CASE('idTclm(iO2_o)')
                idTclm(iO2_o) = varid
              CASE('idTclm(iO3_c)')
                idTclm(iO3_c) = varid
              CASE('idTclm(iO3_TA)')
                idTclm(iO3_TA) = varid
              CASE('idTclm(iR1_c)')
                idTclm(iR1_c) = varid
              CASE('idTclm(iR1_n)')
                idTclm(iR1_n) = varid
              CASE('idTclm(iR1_p)')
                idTclm(iR1_p) = varid
              CASE('idTclm(iR2_c)')
                idTclm(iR2_c) = varid
              CASE('idTclm(iR3_c)')
                idTclm(iR3_c) = varid
              CASE('idTclm(iR4_c)')
                idTclm(iR4_c) = varid
              CASE('idTclm(iR4_n)')
                idTclm(iR4_n) = varid
              CASE('idTclm(iR4_p)')
                idTclm(iR4_p) = varid
              CASE('idTclm(iR6_c)')
                idTclm(iR6_c) = varid
              CASE('idTclm(iR6_n)')
                idTclm(iR6_n) = varid
              CASE('idTclm(iR6_p)')
                idTclm(iR6_p) = varid
              CASE('idTclm(iR6_s)')
                idTclm(iR6_s) = varid
              CASE('idTclm(iR8_c)')
                idTclm(iR8_c) = varid
              CASE('idTclm(iR8_n)')
                idTclm(iR8_n) = varid
              CASE('idTclm(iR8_p)')
                idTclm(iR8_p) = varid
              CASE('idTclm(iR8_s)')
                idTclm(iR8_s) = varid
              CASE('idTclm(iB1_c)')
                idTclm(iB1_c) = varid
              CASE('idTclm(iB1_n)')
                idTclm(iB1_n) = varid
              CASE('idTclm(iB1_p)')
                idTclm(iB1_p) = varid
              CASE('idTclm(iP1_c)')
                idTclm(iP1_c) = varid
              CASE('idTclm(iP1_n)')
                idTclm(iP1_n) = varid
              CASE('idTclm(iP1_p)')
                idTclm(iP1_p) = varid
              CASE('idTclm(iP1_Chl)')
                idTclm(iP1_Chl) = varid
              CASE('idTclm(iP1_s)')
                idTclm(iP1_s) = varid
              CASE('idTclm(iL2_c)')
                idTclm(iL2_c) = varid
              CASE('idTclm(iP2_c)')
                idTclm(iP2_c) = varid
              CASE('idTclm(iP2_n)')
                idTclm(iP2_n) = varid
              CASE('idTclm(iP2_p)')
                idTclm(iP2_p) = varid
              CASE('idTclm(iP2_Chl)')
                idTclm(iP2_Chl) = varid
              CASE('idTclm(iP3_c)')
                idTclm(iP3_c) = varid
              CASE('idTclm(iP3_n)')
                idTclm(iP3_n) = varid
              CASE('idTclm(iP3_p)')
                idTclm(iP3_p) = varid
              CASE('idTclm(iP3_Chl)')
                idTclm(iP3_Chl) = varid
              CASE('idTclm(iP4_c)')
                idTclm(iP4_c) = varid
              CASE('idTclm(iP4_n)')
                idTclm(iP4_n) = varid
              CASE('idTclm(iP4_p)')
                idTclm(iP4_p) = varid
              CASE('idTclm(iP4_Chl)')
                idTclm(iP4_Chl) = varid
              CASE('idTclm(iZ4_c)')
                idTclm(iZ4_c) = varid
              CASE('idTclm(iZ5_c)')
                idTclm(iZ5_c) = varid
              CASE('idTclm(iZ5_n)')
                idTclm(iZ5_n) = varid
              CASE('idTclm(iZ5_p)')
                idTclm(iZ5_p) = varid
              CASE('idTclm(iZ6_c)')
                idTclm(iZ6_c) = varid
              CASE('idTclm(iZ6_n)')
                idTclm(iZ6_n) = varid
              CASE('idTclm(iZ6_p)')
                idTclm(iZ6_p) = varid

/*
**  Adjoint sensitivity state biological tracers.
*/

#if defined AD_SENSITIVITY   || defined IS4DVAR_SENSITIVITY || \
    defined OPT_OBSERVATIONS || defined SENSITIVITY_4DVAR   || \
    defined SO_SEMI
              CASE('idTads(iN1_p)')
                idTads(iN1_p) = varid
              CASE('idTads(iN3_n)')
                idTads(iN3_n) = varid
              CASE('idTads(iN4_n)')
                idTads(iN4_n) = varid
              CASE('idTads(iN5_s)')
                idTads(iN5_s) = varid
              CASE('idTads(iO2_o)')
                idTads(iO2_o) = varid
              CASE('idTads(iO3_c)')
                idTads(iO3_c) = varid
              CASE('idTads(iO3_TA)')
                idTads(iO3_TA) = varid
              CASE('idTads(iR1_c)')
                idTads(iR1_c) = varid
              CASE('idTads(iR1_n)')
                idTads(iR1_n) = varid
              CASE('idTads(iR1_p)')
                idTads(iR1_p) = varid
              CASE('idTads(iR2_c)')
                idTads(iR2_c) = varid
              CASE('idTads(iR3_c)')
                idTads(iR3_c) = varid
              CASE('idTads(iR4_c)')
                idTads(iR4_c) = varid
              CASE('idTads(iR4_n)')
                idTads(iR4_n) = varid
              CASE('idTads(iR4_p)')
                idTads(iR4_p) = varid
              CASE('idTads(iR6_c)')
                idTads(iR6_c) = varid
              CASE('idTads(iR6_n)')
                idTads(iR6_n) = varid
              CASE('idTads(iR6_p)')
                idTads(iR6_p) = varid
              CASE('idTads(iR6_s)')
                idTads(iR6_s) = varid
              CASE('idTads(iR8_c)')
                idTads(iR8_c) = varid
              CASE('idTads(iR8_n)')
                idTads(iR8_n) = varid
              CASE('idTads(iR8_p)')
                idTads(iR8_p) = varid
              CASE('idTads(iR8_s)')
                idTads(iR8_s) = varid
              CASE('idTads(iB1_c)')
                idTads(iB1_c) = varid
              CASE('idTads(iB1_n)')
                idTads(iB1_n) = varid
              CASE('idTads(iB1_p)')
                idTads(iB1_p) = varid
              CASE('idTads(iP1_c)')
                idTads(iP1_c) = varid
              CASE('idTads(iP1_n)')
                idTads(iP1_n) = varid
              CASE('idTads(iP1_p)')
                idTads(iP1_p) = varid
              CASE('idTads(iP1_Chl)')
                idTads(iP1_Chl) = varid
              CASE('idTads(iP1_s)')
                idTads(iP1_s) = varid
              CASE('idTads(iL2_c)')
                idTads(iL2_c) = varid
              CASE('idTads(iP2_c)')
                idTads(iP2_c) = varid
              CASE('idTads(iP2_n)')
                idTads(iP2_n) = varid
              CASE('idTads(iP2_p)')
                idTads(iP2_p) = varid
              CASE('idTads(iP2_Chl)')
                idTads(iP2_Chl) = varid
              CASE('idTads(iP3_c)')
                idTads(iP3_c) = varid
              CASE('idTads(iP3_n)')
                idTads(iP3_n) = varid
              CASE('idTads(iP3_p)')
                idTads(iP3_p) = varid
              CASE('idTads(iP3_Chl)')
                idTads(iP3_Chl) = varid
              CASE('idTads(iP4_c)')
                idTads(iP4_c) = varid
              CASE('idTads(iP4_n)')
                idTads(iP4_n) = varid
              CASE('idTads(iP4_p)')
                idTads(iP4_p) = varid
              CASE('idTads(iP4_Chl)')
                idTads(iP4_Chl) = varid
              CASE('idTads(iZ4_c)')
                idTads(iZ4_c) = varid
              CASE('idTads(iZ5_c)')
                idTads(iZ5_c) = varid
              CASE('idTads(iZ5_n)')
                idTads(iZ5_n) = varid
              CASE('idTads(iZ5_p)')
                idTads(iZ5_p) = varid
              CASE('idTads(iZ6_c)')
                idTads(iZ6_c) = varid
              CASE('idTads(iZ6_n)')
                idTads(iZ6_n) = varid
              CASE('idTads(iZ6_p)')
                idTads(iZ6_p) = varid
#endif
/*
**  Biological tracers open boundary conditions.
*/

              CASE('idTbry(iwest,iN1_p)')
                idTbry(iwest,iN1_p) = varid
              CASE('idTbry(ieast,iN1_p)')
                idTbry(ieast,iN1_p) = varid
              CASE('idTbry(isouth,iN1_p)')
                idTbry(isouth,iN1_p) = varid
              CASE('idTbry(inorth,iN1_p)')
                idTbry(inorth,iN1_p) = varid

              CASE('idTbry(iwest,iN3_n)')
                idTbry(iwest,iN3_n) = varid
              CASE('idTbry(ieast,iN3_n)')
                idTbry(ieast,iN3_n) = varid
              CASE('idTbry(isouth,iN3_n)')
                idTbry(isouth,iN3_n) = varid
              CASE('idTbry(inorth,iN3_n)')
                idTbry(inorth,iN3_n) = varid

              CASE('idTbry(iwest,iN4_n)')
                idTbry(iwest,iN4_n) = varid
              CASE('idTbry(ieast,iN4_n)')
                idTbry(ieast,iN4_n) = varid
              CASE('idTbry(isouth,iN4_n)')
                idTbry(isouth,iN4_n) = varid
              CASE('idTbry(inorth,iN4_n)')
                idTbry(inorth,iN4_n) = varid

              CASE('idTbry(iwest,iN5_s)')
                idTbry(iwest,iN5_s) = varid
              CASE('idTbry(ieast,iN5_s)')
                idTbry(ieast,iN5_s) = varid
              CASE('idTbry(isouth,iN5_s)')
                idTbry(isouth,iN5_s) = varid
              CASE('idTbry(inorth,iN5_s)')
                idTbry(inorth,iN5_s) = varid

              CASE('idTbry(iwest,iO2_o)')
                idTbry(iwest,iO2_o) = varid
              CASE('idTbry(ieast,iO2_o)')
                idTbry(ieast,iO2_o) = varid
              CASE('idTbry(isouth,iO2_o)')
                idTbry(isouth,iO2_o) = varid
              CASE('idTbry(inorth,iO2_o)')
                idTbry(inorth,iO2_o) = varid

              CASE('idTbry(iwest,iO3_c)')
                idTbry(iwest,iO3_c) = varid
              CASE('idTbry(ieast,iO3_c)')
                idTbry(ieast,iO3_c) = varid
              CASE('idTbry(isouth,iO3_c)')
                idTbry(isouth,iO3_c) = varid
              CASE('idTbry(inorth,iO3_c)')
                idTbry(inorth,iO3_c) = varid

              CASE('idTbry(iwest,iO3_TA)')
                idTbry(iwest,iO3_TA) = varid
              CASE('idTbry(ieast,iO3_TA)')
                idTbry(ieast,iO3_TA) = varid
              CASE('idTbry(isouth,iO3_TA)')
                idTbry(isouth,iO3_TA) = varid
              CASE('idTbry(inorth,iO3_TA)')
                idTbry(inorth,iO3_TA) = varid

              CASE('idTbry(iwest,iR1_c)')
                idTbry(iwest,iR1_c) = varid
              CASE('idTbry(ieast,iR1_c)')
                idTbry(ieast,iR1_c) = varid
              CASE('idTbry(isouth,iR1_c)')
                idTbry(isouth,iR1_c) = varid
              CASE('idTbry(inorth,iR1_c)')
                idTbry(inorth,iR1_c) = varid

              CASE('idTbry(iwest,iR1_n)')
                idTbry(iwest,iR1_n) = varid
              CASE('idTbry(ieast,iR1_n)')
                idTbry(ieast,iR1_n) = varid
              CASE('idTbry(isouth,iR1_n)')
                idTbry(isouth,iR1_n) = varid
              CASE('idTbry(inorth,iR1_n)')
                idTbry(inorth,iR1_n) = varid

              CASE('idTbry(iwest,iR1_p)')
                idTbry(iwest,iR1_p) = varid
              CASE('idTbry(ieast,iR1_p)')
                idTbry(ieast,iR1_p) = varid
              CASE('idTbry(isouth,iR1_p)')
                idTbry(isouth,iR1_p) = varid
              CASE('idTbry(inorth,iR1_p)')
                idTbry(inorth,iR1_p) = varid

              CASE('idTbry(iwest,iR2_c)')
                idTbry(iwest,iR2_c) = varid
              CASE('idTbry(ieast,iR2_c)')
                idTbry(ieast,iR2_c) = varid
              CASE('idTbry(isouth,iR2_c)')
                idTbry(isouth,iR2_c) = varid
              CASE('idTbry(inorth,iR2_c)')
                idTbry(inorth,iR2_c) = varid

              CASE('idTbry(iwest,iR3_c)')
                idTbry(iwest,iR3_c) = varid
              CASE('idTbry(ieast,iR3_c)')
                idTbry(ieast,iR3_c) = varid
              CASE('idTbry(isouth,iR3_c)')
                idTbry(isouth,iR3_c) = varid
              CASE('idTbry(inorth,iR3_c)')
                idTbry(inorth,iR3_c) = varid

              CASE('idTbry(iwest,iR4_c)')
                idTbry(iwest,iR4_c) = varid
              CASE('idTbry(ieast,iR4_c)')
                idTbry(ieast,iR4_c) = varid
              CASE('idTbry(isouth,iR4_c)')
                idTbry(isouth,iR4_c) = varid
              CASE('idTbry(inorth,iR4_c)')
                idTbry(inorth,iR4_c) = varid

              CASE('idTbry(iwest,iR4_n)')
                idTbry(iwest,iR4_n) = varid
              CASE('idTbry(ieast,iR4_n)')
                idTbry(ieast,iR4_n) = varid
              CASE('idTbry(isouth,iR4_n)')
                idTbry(isouth,iR4_n) = varid
              CASE('idTbry(inorth,iR4_n)')
                idTbry(inorth,iR4_n) = varid

              CASE('idTbry(iwest,iR4_p)')
                idTbry(iwest,iR4_p) = varid
              CASE('idTbry(ieast,iR4_p)')
                idTbry(ieast,iR4_p) = varid
              CASE('idTbry(isouth,iR4_p)')
                idTbry(isouth,iR4_p) = varid
              CASE('idTbry(inorth,iR4_p)')
                idTbry(inorth,iR4_p) = varid

              CASE('idTbry(iwest,iR6_c)')
                idTbry(iwest,iR6_c) = varid
              CASE('idTbry(ieast,iR6_c)')
                idTbry(ieast,iR6_c) = varid
              CASE('idTbry(isouth,iR6_c)')
                idTbry(isouth,iR6_c) = varid
              CASE('idTbry(inorth,iR6_c)')
                idTbry(inorth,iR6_c) = varid

              CASE('idTbry(iwest,iR6_n)')
                idTbry(iwest,iR6_n) = varid
              CASE('idTbry(ieast,iR6_n)')
                idTbry(ieast,iR6_n) = varid
              CASE('idTbry(isouth,iR6_n)')
                idTbry(isouth,iR6_n) = varid
              CASE('idTbry(inorth,iR6_n)')
                idTbry(inorth,iR6_n) = varid

              CASE('idTbry(iwest,iR6_p)')
                idTbry(iwest,iR6_p) = varid
              CASE('idTbry(ieast,iR6_p)')
                idTbry(ieast,iR6_p) = varid
              CASE('idTbry(isouth,iR6_p)')
                idTbry(isouth,iR6_p) = varid
              CASE('idTbry(inorth,iR6_p)')
                idTbry(inorth,iR6_p) = varid

              CASE('idTbry(iwest,iR6_s)')
                idTbry(iwest,iR6_s) = varid
              CASE('idTbry(ieast,iR6_s)')
                idTbry(ieast,iR6_s) = varid
              CASE('idTbry(isouth,iR6_s)')
                idTbry(isouth,iR6_s) = varid
              CASE('idTbry(inorth,iR6_s)')
                idTbry(inorth,iR6_s) = varid

              CASE('idTbry(iwest,iR8_c)')
                idTbry(iwest,iR8_c) = varid
              CASE('idTbry(ieast,iR8_c)')
                idTbry(ieast,iR8_c) = varid
              CASE('idTbry(isouth,iR8_c)')
                idTbry(isouth,iR8_c) = varid
              CASE('idTbry(inorth,iR8_c)')
                idTbry(inorth,iR8_c) = varid

              CASE('idTbry(iwest,iR8_n)')
                idTbry(iwest,iR8_n) = varid
              CASE('idTbry(ieast,iR8_n)')
                idTbry(ieast,iR8_n) = varid
              CASE('idTbry(isouth,iR8_n)')
                idTbry(isouth,iR8_n) = varid
              CASE('idTbry(inorth,iR8_n)')
                idTbry(inorth,iR8_n) = varid

              CASE('idTbry(iwest,iR8_p)')
                idTbry(iwest,iR8_p) = varid
              CASE('idTbry(ieast,iR8_p)')
                idTbry(ieast,iR8_p) = varid
              CASE('idTbry(isouth,iR8_p)')
                idTbry(isouth,iR8_p) = varid
              CASE('idTbry(inorth,iR8_p)')
                idTbry(inorth,iR8_p) = varid

              CASE('idTbry(iwest,iR8_s)')
                idTbry(iwest,iR8_s) = varid
              CASE('idTbry(ieast,iR8_s)')
                idTbry(ieast,iR8_s) = varid
              CASE('idTbry(isouth,iR8_s)')
                idTbry(isouth,iR8_s) = varid
              CASE('idTbry(inorth,iR8_s)')
                idTbry(inorth,iR8_s) = varid

              CASE('idTbry(iwest,iB1_c)')
                idTbry(iwest,iB1_c) = varid
              CASE('idTbry(ieast,iB1_c)')
                idTbry(ieast,iB1_c) = varid
              CASE('idTbry(isouth,iB1_c)')
                idTbry(isouth,iB1_c) = varid
              CASE('idTbry(inorth,iB1_c)')
                idTbry(inorth,iB1_c) = varid

              CASE('idTbry(iwest,iB1_n)')
                idTbry(iwest,iB1_n) = varid
              CASE('idTbry(ieast,iB1_n)')
                idTbry(ieast,iB1_n) = varid
              CASE('idTbry(isouth,iB1_n)')
                idTbry(isouth,iB1_n) = varid
              CASE('idTbry(inorth,iB1_n)')
                idTbry(inorth,iB1_n) = varid

              CASE('idTbry(iwest,iB1_p)')
                idTbry(iwest,iB1_p) = varid
              CASE('idTbry(ieast,iB1_p)')
                idTbry(ieast,iB1_p) = varid
              CASE('idTbry(isouth,iB1_p)')
                idTbry(isouth,iB1_p) = varid
              CASE('idTbry(inorth,iB1_p)')
                idTbry(inorth,iB1_p) = varid

              CASE('idTbry(iwest,iP1_c)')
                idTbry(iwest,iP1_c) = varid
              CASE('idTbry(ieast,iP1_c)')
                idTbry(ieast,iP1_c) = varid
              CASE('idTbry(isouth,iP1_c)')
                idTbry(isouth,iP1_c) = varid
              CASE('idTbry(inorth,iP1_c)')
                idTbry(inorth,iP1_c) = varid

              CASE('idTbry(iwest,iP1_n)')
                idTbry(iwest,iP1_n) = varid
              CASE('idTbry(ieast,iP1_n)')
                idTbry(ieast,iP1_n) = varid
              CASE('idTbry(isouth,iP1_n)')
                idTbry(isouth,iP1_n) = varid
              CASE('idTbry(inorth,iP1_n)')
                idTbry(inorth,iP1_n) = varid

              CASE('idTbry(iwest,iP1_p)')
                idTbry(iwest,iP1_p) = varid
              CASE('idTbry(ieast,iP1_p)')
                idTbry(ieast,iP1_p) = varid
              CASE('idTbry(isouth,iP1_p)')
                idTbry(isouth,iP1_p) = varid
              CASE('idTbry(inorth,iP1_p)')
                idTbry(inorth,iP1_p) = varid

              CASE('idTbry(iwest,iP1_Chl)')
                idTbry(iwest,iP1_Chl) = varid
              CASE('idTbry(ieast,iP1_Chl)')
                idTbry(ieast,iP1_Chl) = varid
              CASE('idTbry(isouth,iP1_Chl)')
                idTbry(isouth,iP1_Chl) = varid
              CASE('idTbry(inorth,iP1_Chl)')
                idTbry(inorth,iP1_Chl) = varid

              CASE('idTbry(iwest,iP1_s)')
                idTbry(iwest,iP1_s) = varid
              CASE('idTbry(ieast,iP1_s)')
                idTbry(ieast,iP1_s) = varid
              CASE('idTbry(isouth,iP1_s)')
                idTbry(isouth,iP1_s) = varid
              CASE('idTbry(inorth,iP1_s)')
                idTbry(inorth,iP1_s) = varid

              CASE('idTbry(iwest,iL2_c)')
                idTbry(iwest,iL2_c) = varid
              CASE('idTbry(ieast,iL2_c)')
                idTbry(ieast,iL2_c) = varid
              CASE('idTbry(isouth,iL2_c)')
                idTbry(isouth,iL2_c) = varid
              CASE('idTbry(inorth,iL2_c)')
                idTbry(inorth,iL2_c) = varid

              CASE('idTbry(iwest,iP2_c)')
                idTbry(iwest,iP2_c) = varid
              CASE('idTbry(ieast,iP2_c)')
                idTbry(ieast,iP2_c) = varid
              CASE('idTbry(isouth,iP2_c)')
                idTbry(isouth,iP2_c) = varid
              CASE('idTbry(inorth,iP2_c)')
                idTbry(inorth,iP2_c) = varid

              CASE('idTbry(iwest,iP2_n)')
                idTbry(iwest,iP2_n) = varid
              CASE('idTbry(ieast,iP2_n)')
                idTbry(ieast,iP2_n) = varid
              CASE('idTbry(isouth,iP2_n)')
                idTbry(isouth,iP2_n) = varid
              CASE('idTbry(inorth,iP2_n)')
                idTbry(inorth,iP2_n) = varid

              CASE('idTbry(iwest,iP2_p)')
                idTbry(iwest,iP2_p) = varid
              CASE('idTbry(ieast,iP2_p)')
                idTbry(ieast,iP2_p) = varid
              CASE('idTbry(isouth,iP2_p)')
                idTbry(isouth,iP2_p) = varid
              CASE('idTbry(inorth,iP2_p)')
                idTbry(inorth,iP2_p) = varid

              CASE('idTbry(iwest,iP2_Chl)')
                idTbry(iwest,iP2_Chl) = varid
              CASE('idTbry(ieast,iP2_Chl)')
                idTbry(ieast,iP2_Chl) = varid
              CASE('idTbry(isouth,iP2_Chl)')
                idTbry(isouth,iP2_Chl) = varid
              CASE('idTbry(inorth,iP2_Chl)')
                idTbry(inorth,iP2_Chl) = varid

              CASE('idTbry(iwest,iP3_c)')
                idTbry(iwest,iP3_c) = varid
              CASE('idTbry(ieast,iP3_c)')
                idTbry(ieast,iP3_c) = varid
              CASE('idTbry(isouth,iP3_c)')
                idTbry(isouth,iP3_c) = varid
              CASE('idTbry(inorth,iP3_c)')
                idTbry(inorth,iP3_c) = varid

              CASE('idTbry(iwest,iP3_n)')
                idTbry(iwest,iP3_n) = varid
              CASE('idTbry(ieast,iP3_n)')
                idTbry(ieast,iP3_n) = varid
              CASE('idTbry(isouth,iP3_n)')
                idTbry(isouth,iP3_n) = varid
              CASE('idTbry(inorth,iP3_n)')
                idTbry(inorth,iP3_n) = varid

              CASE('idTbry(iwest,iP3_p)')
                idTbry(iwest,iP3_p) = varid
              CASE('idTbry(ieast,iP3_p)')
                idTbry(ieast,iP3_p) = varid
              CASE('idTbry(isouth,iP3_p)')
                idTbry(isouth,iP3_p) = varid
              CASE('idTbry(inorth,iP3_p)')
                idTbry(inorth,iP3_p) = varid

              CASE('idTbry(iwest,iP3_Chl)')
                idTbry(iwest,iP3_Chl) = varid
              CASE('idTbry(ieast,iP3_Chl)')
                idTbry(ieast,iP3_Chl) = varid
              CASE('idTbry(isouth,iP3_Chl)')
                idTbry(isouth,iP3_Chl) = varid
              CASE('idTbry(inorth,iP3_Chl)')
                idTbry(inorth,iP3_Chl) = varid

              CASE('idTbry(iwest,iP4_c)')
                idTbry(iwest,iP4_c) = varid
              CASE('idTbry(ieast,iP4_c)')
                idTbry(ieast,iP4_c) = varid
              CASE('idTbry(isouth,iP4_c)')
                idTbry(isouth,iP4_c) = varid
              CASE('idTbry(inorth,iP4_c)')
                idTbry(inorth,iP4_c) = varid

              CASE('idTbry(iwest,iP4_n)')
                idTbry(iwest,iP4_n) = varid
              CASE('idTbry(ieast,iP4_n)')
                idTbry(ieast,iP4_n) = varid
              CASE('idTbry(isouth,iP4_n)')
                idTbry(isouth,iP4_n) = varid
              CASE('idTbry(inorth,iP4_n)')
                idTbry(inorth,iP4_n) = varid

              CASE('idTbry(iwest,iP4_p)')
                idTbry(iwest,iP4_p) = varid
              CASE('idTbry(ieast,iP4_p)')
                idTbry(ieast,iP4_p) = varid
              CASE('idTbry(isouth,iP4_p)')
                idTbry(isouth,iP4_p) = varid
              CASE('idTbry(inorth,iP4_p)')
                idTbry(inorth,iP4_p) = varid

              CASE('idTbry(iwest,iP4_Chl)')
                idTbry(iwest,iP4_Chl) = varid
              CASE('idTbry(ieast,iP4_Chl)')
                idTbry(ieast,iP4_Chl) = varid
              CASE('idTbry(isouth,iP4_Chl)')
                idTbry(isouth,iP4_Chl) = varid
              CASE('idTbry(inorth,iP4_Chl)')
                idTbry(inorth,iP4_Chl) = varid

              CASE('idTbry(iwest,iZ4_c)')
                idTbry(iwest,iZ4_c) = varid
              CASE('idTbry(ieast,iZ4_c)')
                idTbry(ieast,iZ4_c) = varid
              CASE('idTbry(isouth,iZ4_c)')
                idTbry(isouth,iZ4_c) = varid
              CASE('idTbry(inorth,iZ4_c)')
                idTbry(inorth,iZ4_c) = varid

              CASE('idTbry(iwest,iZ5_c)')
                idTbry(iwest,iZ5_c) = varid
              CASE('idTbry(ieast,iZ5_c)')
                idTbry(ieast,iZ5_c) = varid
              CASE('idTbry(isouth,iZ5_c)')
                idTbry(isouth,iZ5_c) = varid
              CASE('idTbry(inorth,iZ5_c)')
                idTbry(inorth,iZ5_c) = varid

              CASE('idTbry(iwest,iZ5_n)')
                idTbry(iwest,iZ5_n) = varid
              CASE('idTbry(ieast,iZ5_n)')
                idTbry(ieast,iZ5_n) = varid
              CASE('idTbry(isouth,iZ5_n)')
                idTbry(isouth,iZ5_n) = varid
              CASE('idTbry(inorth,iZ5_n)')
                idTbry(inorth,iZ5_n) = varid

              CASE('idTbry(iwest,iZ5_p)')
                idTbry(iwest,iZ5_p) = varid
              CASE('idTbry(ieast,iZ5_p)')
                idTbry(ieast,iZ5_p) = varid
              CASE('idTbry(isouth,iZ5_p)')
                idTbry(isouth,iZ5_p) = varid
              CASE('idTbry(inorth,iZ5_p)')
                idTbry(inorth,iZ5_p) = varid

              CASE('idTbry(iwest,iZ6_c)')
                idTbry(iwest,iZ6_c) = varid
              CASE('idTbry(ieast,iZ6_c)')
                idTbry(ieast,iZ6_c) = varid
              CASE('idTbry(isouth,iZ6_c)')
                idTbry(isouth,iZ6_c) = varid
              CASE('idTbry(inorth,iZ6_c)')
                idTbry(inorth,iZ6_c) = varid

              CASE('idTbry(iwest,iZ6_n)')
                idTbry(iwest,iZ6_n) = varid
              CASE('idTbry(ieast,iZ6_n)')
                idTbry(ieast,iZ6_n) = varid
              CASE('idTbry(isouth,iZ6_n)')
                idTbry(isouth,iZ6_n) = varid
              CASE('idTbry(inorth,iZ6_n)')
                idTbry(inorth,iZ6_n) = varid

              CASE('idTbry(iwest,iZ6_p)')
                idTbry(iwest,iZ6_p) = varid
              CASE('idTbry(ieast,iZ6_p)')
                idTbry(ieast,iZ6_p) = varid
              CASE('idTbry(isouth,iZ6_p)')
                idTbry(isouth,iZ6_p) = varid
              CASE('idTbry(inorth,iZ6_p)')
                idTbry(inorth,iZ6_p) = varid


/*
**  Biological tracers point Source/Sinks (river runoff)..
*/

              CASE('idRtrc(iN1_p)')
                idRtrc(iN1_p) = varid
              CASE('idRtrc(iN3_n)')
                idRtrc(iN3_n) = varid
              CASE('idRtrc(iN4_n)')
                idRtrc(iN4_n) = varid
              CASE('idRtrc(iN5_s)')
                idRtrc(iN5_s) = varid
              CASE('idRtrc(iO2_o)')
                idRtrc(iO2_o) = varid
              CASE('idRtrc(iO3_c)')
                idRtrc(iO3_c) = varid
              CASE('idRtrc(iO3_TA)')
                idRtrc(iO3_TA) = varid
              CASE('idRtrc(iR1_c)')
                idRtrc(iR1_c) = varid
              CASE('idRtrc(iR1_n)')
                idRtrc(iR1_n) = varid
              CASE('idRtrc(iR1_p)')
                idRtrc(iR1_p) = varid
              CASE('idRtrc(iR2_c)')
                idRtrc(iR2_c) = varid
              CASE('idRtrc(iR3_c)')
                idRtrc(iR3_c) = varid
              CASE('idRtrc(iR4_c)')
                idRtrc(iR4_c) = varid
              CASE('idRtrc(iR4_n)')
                idRtrc(iR4_n) = varid
              CASE('idRtrc(iR4_p)')
                idRtrc(iR4_p) = varid
              CASE('idRtrc(iR6_c)')
                idRtrc(iR6_c) = varid
              CASE('idRtrc(iR6_n)')
                idRtrc(iR6_n) = varid
              CASE('idRtrc(iR6_p)')
                idRtrc(iR6_p) = varid
              CASE('idRtrc(iR6_s)')
                idRtrc(iR6_s) = varid
              CASE('idRtrc(iR8_c)')
                idRtrc(iR8_c) = varid
              CASE('idRtrc(iR8_n)')
                idRtrc(iR8_n) = varid
              CASE('idRtrc(iR8_p)')
                idRtrc(iR8_p) = varid
              CASE('idRtrc(iR8_s)')
                idRtrc(iR8_s) = varid
              CASE('idRtrc(iB1_c)')
                idRtrc(iB1_c) = varid
              CASE('idRtrc(iB1_n)')
                idRtrc(iB1_n) = varid
              CASE('idRtrc(iB1_p)')
                idRtrc(iB1_p) = varid
              CASE('idRtrc(iP1_c)')
                idRtrc(iP1_c) = varid
              CASE('idRtrc(iP1_n)')
                idRtrc(iP1_n) = varid
              CASE('idRtrc(iP1_p)')
                idRtrc(iP1_p) = varid
              CASE('idRtrc(iP1_Chl)')
                idRtrc(iP1_Chl) = varid
              CASE('idRtrc(iP1_s)')
                idRtrc(iP1_s) = varid
              CASE('idRtrc(iL2_c)')
                idRtrc(iL2_c) = varid
              CASE('idRtrc(iP2_c)')
                idRtrc(iP2_c) = varid
              CASE('idRtrc(iP2_n)')
                idRtrc(iP2_n) = varid
              CASE('idRtrc(iP2_p)')
                idRtrc(iP2_p) = varid
              CASE('idRtrc(iP2_Chl)')
                idRtrc(iP2_Chl) = varid
              CASE('idRtrc(iP3_c)')
                idRtrc(iP3_c) = varid
              CASE('idRtrc(iP3_n)')
                idRtrc(iP3_n) = varid
              CASE('idRtrc(iP3_p)')
                idRtrc(iP3_p) = varid
              CASE('idRtrc(iP3_Chl)')
                idRtrc(iP3_Chl) = varid
              CASE('idRtrc(iP4_c)')
                idRtrc(iP4_c) = varid
              CASE('idRtrc(iP4_n)')
                idRtrc(iP4_n) = varid
              CASE('idRtrc(iP4_p)')
                idRtrc(iP4_p) = varid
              CASE('idRtrc(iP4_Chl)')
                idRtrc(iP4_Chl) = varid
              CASE('idRtrc(iZ4_c)')
                idRtrc(iZ4_c) = varid
              CASE('idRtrc(iZ5_c)')
                idRtrc(iZ5_c) = varid
              CASE('idRtrc(iZ5_n)')
                idRtrc(iZ5_n) = varid
              CASE('idRtrc(iZ5_p)')
                idRtrc(iZ5_p) = varid
              CASE('idRtrc(iZ6_c)')
                idRtrc(iZ6_c) = varid
              CASE('idRtrc(iZ6_n)')
                idRtrc(iZ6_n) = varid
              CASE('idRtrc(iZ6_p)')
                idRtrc(iZ6_p) = varid
